### ISSUE TITLE
excel_haplotype.py file missing

### ISSUE THREAD

**Issue by abdeltoure** [fengcong3/HAPPE#1]
Hello,
I am trying to install and use your program but I cannot find the file excel_haplotype.py.
It is referenced in the __init___.py script and I get an error when trying to install it. 
Then when I do replace from .excel_haplotype import main_1, the program stops at a clustering step.
Would you please help me with that ?
Best regards,
Abdel

**Comment by fengcong3** [comment]
Hi,
I have fixed this bug, you can clean the old version and reinstall it.
Best,
